- id: circle-ci-validator
  name: CircleCI Config Validation
  description: Validate CircleCI config without having to install the cli globally
  entry: env CIRCLECI_CLI_SKIP_UPDATE_CHECK=true circleci config validate
  language: python
  files: \.circleci/config.yml
